#!/bin/bash

SCRIPTROOT=`dirname $(readlink -f $0)`
BUILDROOT=/srv/kickstart/cloudstack/buildroot
KICKSTART="CentOS-6.4-x86_64-swisstxt.ks"
ISO_URL=http://mirror.switch.ch/ftp/mirror/centos/6.4/isos/x86_64/CentOS-6.4-x86_64-netinstall.iso

ISO_NAME=`basename $ISO_URL`
TAG=`cd $SCRIPTROOT; git tag | tail -n 1`
ISO_GEN_NAME=`echo $ISO_NAME | sed 's/....$//'`-swisstxt-$TAG

cleanup() {
  mount | grep -q $ISO_NAME && umount mnt
  rm -rf build/*
}

# exit on failure
set -e

# change to buildroot
cd $BUILDROOT

# setup dirs
mkdir -p {dist,mnt,build,gen}

# clean up
cleanup

# fetch iso
test -f dist/$ISO_NAME || wget -nc -O dist/$ISO_NAME $ISO_URL

# mount iso
mount -o loop dist/$ISO_NAME mnt

# cp files to build
cp -a mnt/* build

# add kickstart
cp $SCRIPTROOT/$KICKSTART build/isolinux/custom.ks

# add ks option to boot menu entries
sed -i 's/append/append ks=cdrom:custom.ks/' build/isolinux/isolinux.cfg

# set boot menu timeout to 5s
sed -i 's/timeout.*/timeout 5/' build/isolinux/isolinux.cfg

# build iso
mkisofs -o gen/$ISO_GEN_NAME.iso -r -R -J -input-charset utf-8 \
  -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table \
  -V "CentOS 6" -A "CentOS 6" -p Six -T build/isolinux/

# register in cloudstack 
# https://gist.github.com/lonefreak/4026896
cloudstack_api.sh command=listIsos | grep -q $ISO_GEN_NAME || 
cloudstack_api.sh command=registerIso \
  name=""$ISO_GEN_NAME \
  displaytext="https://bitbucket.org/swisstxt/kickstart-iso" \
  url="http://ks.swisstxt.ch/cloudstack/buildroot/gen/$ISO_GEN_NAME.iso" \
  zoneid="-1" \
  isfeatured="true" \
  ispublic="true" \
  ostypeid="ad90197c-31ab-4dce-be17-08463f5634c9"

# clean up
cleanup

# EOF
